[package]
name = "pillow"
version = "0.1.0"
authors = ["Mel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.2"

[dev-dependencies]
rand = "0.7.3"